### ISSUE TITLE
cannot install on jruby

### ISSUE THREAD

**Issue by ghost** [pry/pry-stack_explorer#14]
Currently using jruby jruby-1.7.2 on Ubuntu 12.04.2
# jruby -S gem install pry-stack_explorer

Fetching: debug_inspector-0.0.2.gem (100%)
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
ERROR:  Error installing pry-stack_explorer:
    ERROR: Failed to build gem native extension.

```
    /opt/jruby-1.7.2/bin/jruby extconf.rb
```

NotImplementedError: C extension support is not enabled. Pass -Xcext.enabled=true to JRuby or set JRUBY_OPTS or modify .jrubyrc to enable.

   (root) at /opt/jruby-1.7.2/lib/ruby/shared/mkmf.rb:8
  require at org/jruby/RubyKernel.java:1027
   (root) at /opt/jruby-1.7.2/lib/ruby/shared/rubygems/custom_require.rb:1
   (root) at extconf.rb:19

Gem files will remain installed in /opt/jruby-1.7.2/lib/ruby/gems/shared/gems/binding_of_caller-0.7.1 for inspection.
Results logged to /opt/jruby-1.7.2/lib/ruby/gems/shared/gems/binding_of_caller-0.7.1/ext/binding_of_caller/gem_make.out
# cat /opt/jruby-1.7.2/lib/ruby/gems/shared/gems/binding_of_caller-0.7.1/ext/binding_of_caller/gem_make.out

/opt/jruby-1.7.2/bin/jruby extconf.rb
NotImplementedError: C extension support is not enabled. Pass -Xcext.enabled=true to JRuby or set JRUBY_OPTS or modify .jrubyrc to enable.

   (root) at /opt/jruby-1.7.2/lib/ruby/shared/mkmf.rb:8
  require at org/jruby/RubyKernel.java:1027
   (root) at /opt/jruby-1.7.2/lib/ruby/shared/rubygems/custom_require.rb:1
   (root) at extconf.rb:19

**Comment by samarism** [comment]
Any idea when jruby support will come?
