### ISSUE TITLE
possible to use BacktraceCleaner?

### ISSUE THREAD

**Issue by dchersey** [pry/pry-stack_explorer#17]
Is it possible to use ActiveSupport::Backtrace cleaner in conjunction to filter out gem and rails clutter from the backtrace? 

Something like: 

bc = ActiveSupport::BacktraceCleaner.new
bc.add_filter { | line | line.gsub(Rails.root.to_s, '' }
bc.add_silencer { | line | line =~ /vendor/ }

then to use stack explorer on a filtered backtrace (bc.clean)?

**Comment by joallard** [comment]
Closing in favor of #23, I'll check it out!
