### ISSUE TITLE
Abbreviation for show-stack command?

### ISSUE THREAD

**Issue by pdxwolfy** [pry/pry-stack_explorer#27]
I'm trying to create an abbreviation for the show-stack command, but it is unfortunately not woking:

```
  Pry.commands.alias_command "bt", "show-stack"
```

which yields:

```
1] pry(main)> bt
NameError: undefined local variable or method `bt' for main:Object
from (pry):1:in `get_scores'
```

when I try to use it. Any suggestions on how to accomplish this? TIA.

**Comment by joallard** [comment]
Interesting! I wonder what keyword would work best for most people

**Comment by pdxwolfy** [comment]
I got `bt` from the perl debugger where it stands for backtrace I think.

**Comment by joallard** [comment]
Track #50
