### ISSUE TITLE
RubyGems “Source Code” Links to Old Repo

### ISSUE THREAD

**Issue by trueheart78** [pry/pry-stack_explorer#60]
See conversation here: https://groups.google.com/g/rubygems-org/c/do9wPYLmw74/m/Y6pEuW6pBQAJ?pli=1

## Overview

On https://rubygems.org/gems/pry-stack_explorer the "Homepage" correctly links to https://github.com/pry/pry-stack_explorer while the "Source Code" link points to the old repository code at https://github.com/banister/pry-stack_explorer

Yes, the "Source Code" repo does make it clear that the gem has moved, but if you're like me, doing a Ruby compatibility upgrade for a project, you tend to click "Source Code" and then go directly to the Changelog file, if there is no "Changelog" link on the Rubygems.org page.

## Response from Support 

The gems themselves control these links, you'll need to tell the gem author.

💖

**Comment by kbrock** [comment]
Thanks for following through @trueheart78 

Looks like the metadata was added 14 days ago.

The metadata will get fixed by the next push. It may be worth bumping to 6.0.1 just to update the metadata.

**Comment by kbrock** [comment]
ooh, consider adding https://github.com/pry/pry-stack_explorer/pull/61 before you push.

That is what true heart wanted in the first place :)

**Comment by trueheart78** [comment]
Awesome! Thanks 💖

**Comment by joallard** [comment]
Sounds to me like this is fixed by #61. Thanks!
